server:
  port: 8090

spring:
  data:
    mongodb:
      database: edu_comment
      host: 113.31.105.128
      port: 27017
  klock:
    address: 113.31.105.128:6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    #启用shutdown端点，以便支持优雅停机
    shutdown:
      enabled: true

#分布式链路追踪--调整SpringBoot日志输出级别
logging:
  config: classpath:logback.xml